### ISSUE TITLE
sucess parameter is unclear

### ISSUE THREAD

**Issue by sebi06** [apeer-micro/apeer-python-sdk#7]
The idea with the success parameter is nice, but poorly explained (sorry)

- Is this one supposed to be visible inside the UI?
- Or is this just useful for internal purposes?
 "Who" or "what" sets success to True or False?

This is not clear straight away for "normal users". We should really post here a complete example including the JSON for the module spec, otherwise most people will not be able to understand this.

**Comment by nitish-tripathi** [comment]
Our first aim was to get the code up and running. You are right. The more documentation we have the better it is. We want to as easier as possible for normal users to understand and use. We will discuss how to make it better

**Comment by thomasirmer** [comment]
The sample in this repository should also only show how the ADK is being used. We also discussed to move out module examples to GitHub entirely. We could then easily reference those repositories. The sample code here is not intended to be a working example.

**Comment by sebi06** [comment]
I know, but my "gutfeeling" tells me that people expect exactly this ...

**Comment by thomasirmer** [comment]
Then my suggestion is the following. We add a sensible and working example here and remove it as soon as we have the “real” examples on github. We then just reference those

**Comment by nitish-tripathi** [comment]
I am writing wiki as a step by step tutorial to help users create module
https://github.com/apeer-micro/apeer-python-sdk/wiki

Would be awesome if you guys would also contribute to it. I am closing the issue, since I have started working on it
